[set]

# VLSI-05

# batch_size = 80
# num_workers = 0
# device_ids = [0, 1]

#VLSI-02

batch_size = 1
num_workers = 0
device_ids = [3]

# Autodl

# batch_size = 256
# #512
# device_ids = [0, 1, 2, 3, 4, 5, 6, 7]
# num_workers = 40

user = root
compress = scripts/YAML/prune_quant_sensitivity_module.yaml
;resumed_checkpoint_path = /root/auto-nas/_epoch-53_best.pth.tar

epoch_start_valtest = 30
extract = false


[fine]
threshold_lr_x = 400
threshold_lr_factor = 0.7
lambda = 0
bias = 0
